//auth action types
export const START_AUTH = "START_AUTH";
export const SUCCESS_AUTH = "SUCCESS";
export const SUCCESS_UPLOAD = "SUCCESS_UPLOAD";
export const FAIL_AUTH = "FAIL_AUTH";
export const LOGOUT_AUTH = "LOGOUT_AUTH";
export const SET_LOGGED_USER = "SET_LOGGED_USER";

//product action
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const SET_PRODUCT_FILTER_TYPE = "SET_PRODUCT_FILTER_TYPE";
export const SET_PRODUCT_FILTER_TYPE_REQUEST =
  "SET_PRODUCT_FILTER_TYPE_REQUEST";
export const SET_PRODUCT_FILTER_TEXT = "SET_PRODUCT_FILTER_TEXT";
export const SET_PRODUCT_FILTER_TEXT_REQUEST =
  "SET_PRODUCT_FILTER_TEXT_REQUEST";
export const CREATE_PRODUCT_REVIEW = "CREATE_PRODUCT_REVIEW";

//cart Actions types
export const GET_USER_CART = "GET_USER_CART";
export const SET_USER_CART = "SET_USER_CART";
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";
export const ADD_TO_PRODUCT_QUANTITY = "ADD_TO_PRODUCT_QUANTITY";
export const REMOVE_FROM_PRODUCT_QUANTITY = "REMOVE_FROM_PRODUCT_QUANTITY";
export const CLEAR_CART = "CLEAR_CART";
export const PURCHASE_SUCCESS = "PURCHASE_SUCCESS";
